### ISSUE TITLE
More detail on how this works please?

### ISSUE THREAD

**Issue by ghost** [derBroBro/node-red-contrib-thingspeak#1]
Anybody tried this new node? 

It has 3 fields to complete: 
- Name:
- Write Key:
- Field ID:

It does not seam to work for me, I added the write key, and in <Field ID> msg.payload - also tried 1, not working?
And, does the Write key have to be in quotes, or just plain?

**Comment by derBroBro** [comment]
Hello,

I tried the node for some weeks and it worked as expected. 
You just have to insert the write key (without quotes) and the field id (for example 1, also without quotes). 

Than the msg.payload should be published.

Please note that because thingspeak.com has an API limit, only an update every 15s (per channel) is possible.

Best Malte

**Comment by derBroBro** [comment]
Did it work or do you need further information?

**Comment by ghost** [comment]
Sorry, got it working, maybe some text for the next guy?

**Comment by derBroBro** [comment]
Hello added more speaking placeholders in version 0.0.3

**Comment by ghost** [comment]
Thank you!
